services:
  website:
    build: ./website
    ports:
      - "8000:8000"
    volumes:
      - ./website:/website  # Mapea tu carpeta local 'website' al '/website' en el contenedor
    command: python manage.py runserver 0.0.0.0:8000

  service_generate:
    build: ./service_generate
    ports:
      - "5000:5000"
    volumes:
      - ./service_generate:/app  
    command: python app.py

  service_translate:
    build: ./service_translate
    ports:
      - "5001:5001"
    volumes:
      - ./service_translate:/app  
    command: python app.py

  service_edit:
    build: ./service_edit
    ports:
      - "5002:5002"
    volumes:
      - ./service_edit:/app  
    command: python app.py

  service_transcribe:
    build: ./service_transcribe
    ports:
      - "5003:5003"
    volumes:
      - ./service_transcribe:/app  
    command: python app.py

  service_analyze:
    build: ./service_analyze
    ports:
      - "5004:5004"
    volumes:
      - ./service_analyze:/app  
    command: python app.py

  service_summarize:
    build: ./service_summarize
    ports:
      - "5005:5005"
    volumes:
      - ./service_summarize:/app  
    command: python app.py
