services:

  website:
    build: ./website
    ports:
      - "8000:8000"
    volumes:
      - ./website:/website 
    command: python manage.py runserver 0.0.0.0:8000

  agents:
    build: ./agents
    ports:
      - "5000:5000"
    volumes:
      - ./agents:/agents  
    command: python app.py runserver 0.0.0.0:5000

  embedding:
    build: ./embedding
    ports:
      - "6000:6000"
    volumes:
      - ./embedding:/embedding  
    command: python app.py runserver 0.0.0.0:6000

