# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app



# Copia el código fuente del servicio al contenedor
COPY app/ ./app





# Comando para ejecutar el servicio
CMD ["python", "app/main.py"]  # Cambia según sea necesario